### ISSUE TITLE
Unable to open Network -> My settings in Sugar Desktop.

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/sugar#835]
I got this in logs, might be related to it

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/jarabe/controlpanel/gui.py", line 458, in __select_option_cb
    self.show_section_view(option)
  File "/usr/lib/python2.7/dist-packages/jarabe/controlpanel/gui.py", line 307, in show_section_view
    globals(), locals(), ['model'])
  File "/usr/share/sugar/extensions/cpsection/network/model.py", line 21, in <module>
    gi.require_version('NMClient', '1.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace NMClient not available
```
Using Ubuntu 18.04. Sugar v0.112.

**Comment by quozl** [comment]
Missing dependency.  Please;

`sudo apt install gir1.2-networkmanager-1.0`

Thanks!

**Comment by Aniket21mathur** [comment]
Thanks. Worked!
