### ISSUE TITLE
Neighbourhood view not updated on shared activity stop

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#840]
When an invited user stops a shared activity, the neighbourhood view may be incorrectly updated.

Reproducer;
* on instance one, start and share the CollabWrapper test activity,
* on instance two, join the shared activity from the neighbourhood view, then stop it

Observed behaviour;
* on instance one, two buddy icons are shown on neighbourhood view for instance two,
* on instance two, the buddy icon for instance one may disappear and reappear,

Expected behaviour;

* on instance one, one buddy icon should be shown for instance two,
* on instance two, no change to neighbourhood view,

Instance one shell.log;
```log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jarabe/desktop/meshbox.py", line 409, in _buddy_removed_cb
    self._remove_buddy(buddy_model)
  File "/usr/local/lib/python2.7/dist-packages/jarabe/desktop/meshbox.py", line 435, in _remove_buddy
    icon = self._buddies[buddy_model.props.key]
KeyError: dbus.ByteArray('AAAAB...Y85WlA==', variant_level=1)
```

Instance two shell.log;
```log
1560310543.375053 ERROR root: set_active() failed: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

_org.freedesktop.DBus.Error.NoReply_ is caused by premature termination of the _telepathy-salut_ process before it replies to a message.

On instance two at the time of the event, the process ID of the _telepathy-salut_ process changes, and on Ubuntu 19.04 and an apport crash file is added to `/var/crash` on behalf of the process.

The problem is always reproducible and repeatable.

Theory; a message sent to Telepathy Salut causes it to crash.  It should not crash.  This is a bug in Telepathy Salut, possibly combined with a bug in Sugar usage of the API.

**Comment by aperezbios** [comment]
Was this against a released version of Sugar, top-of-trunk, or a branch?

**Comment by quozl** [comment]
Yes.

**Comment by aperezbios** [comment]
All of the above?

**Comment by quozl** [comment]
Sure, that's another way of looking at it.  At least released versions 0.112, 0.113, 0.114, _master_, and _python3_ branches are affected, as are the branches in development for TelepathyGLib porting.

**Comment by Aniket21mathur** [comment]
My question might be off-topic.
I went through the dbus documentation and classes. We are using [dbus.ByteArray](https://dbus.freedesktop.org/doc/dbus-python/dbus.html#dbus.ByteArray) class. But as per the documentation it takes only one `str` argument. `variant_level` is taken as an argument by `dbus.Byte` class.
I don't know whether my question is relevant, just had it in my mind so posted. :sweat_smile: .
Thanks!

**Comment by quozl** [comment]
_variant_level_ is an argument for _dbus.Byte_, so it is logical by inheritance that it is available for use in a _dbus.ByteArray_.

```
% python
Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbus
>>> x = dbus.ByteArray('test')
>>> x
dbus.ByteArray('test')
>>> x = dbus.ByteArray('test', variant_level=0)
>>> x
dbus.ByteArray('test')
>>> x = dbus.ByteArray('test', variant_level=2)
>>> x
dbus.ByteArray('test', variant_level=2)
>>> x = dbus.ByteArray('test', freddy=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'freddy' is an invalid keyword argument for this function
>>> █
```

**Comment by Aniket21mathur** [comment]
Thanks for explaining. :-).

**Comment by quozl** [comment]
Summary: Debug a Telepathy crash

Sugar uses the Telepathy API for collaboration. Every time a collaboration stops, one of the Telepathy programs crashes with a core dump. It has been happening for a few years.

See if you can use gdb and the Telepathy source code to find out what the problem is! A task for experts. You may have to reach out to the Telepathy project as well.

**Comment by shaansubbaiah** [comment]
@quozl I'm able to reproduce the error in the _instance two_ example differently.

**Reproduced by:** Closing any activity. 
(Tested on the fructose set, this happens on the Log activity as well, which is not a shared activity)

**Error:** 
```
ERROR root: set_active() failed: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

**Tested on:** Sugar 117-3, Debian 10.4 Buster

**Comment by quozl** [comment]
Thanks, but it makes no difference.  Telepathy Salut is still crashing, and it should not.  It is the Telepathy Salut process on _instance two_ that crashes, hence the _set_active_ message.  It is, however, useful to know the same problem persists in 0.117 Debian package 3.  Perhaps the same version of Telepathy is used.

**Comment by srevinsaju** [comment]
I am not sure; I have logs related to `telepathy-salut`, and I guess @quozl might have seen some other logs of mine related to telepathy_Salut. In case it helps
```
1591852813.812322 WARNING root: Connection /org/freedesktop/Telepathy/Connection/salut/local_xmpp/e2782320 does not support OLPC buddy properties
/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py:1644: Warning: g_value_type_compatible: assertion 'src_type' failed
  return _Gtk_main(*args, **kwargs)
/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py:1644: Warning: unable to set property 'buddy' of type 'PyObject' from value of type '(null)'
  return _Gtk_main(*args, **kwargs)
1591852839.673118 ERROR root: set_active() failed: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

(metacity:4459): metacity-WARNING **: 08:20:43.682: CurrentTime used to choose focus window; focus window may not be correct.
```

**Comment by quozl** [comment]
No, it doesn't help, it confuses.  "does not support OLPC buddy properties" is a different problem; compare your version of Telepathy Salut, we're using 0.8.1 with Ubuntu 20.04.  "NoReply" is the same underlying problem.

**Comment by aperezbios** [comment]
for future reference, since I just ran across this issue @srevinsaju ran across back in June, inside the SoaS Fedora nightly image:

In the latest Fedora Rawhide (will soon become 34) SoaS images, telepathy-salut is version 0.8.1, and python3-gwebsockets is version 0.7

**Comment by srevinsaju** [comment]
For the completion of my answer that time, I was using `v0.8.1` using that time. 

Tested again, have the same error. `v0.8.1.r7`, `gwessockets`on v0.7 and `metacity` on v3.38.0

**Comment by quozl** [comment]
Indeed.  It needs diagnosis by debugging Telepathy, or reviewing Telepathy commits.  My guess is the support for Sugar may have been removed from Telepathy because it was not maintained.

**Comment by aperezbios** [comment]
This still happens under Sugar 0.118 in the Fedora Rawhide nightly composes. Upon examining the source repo for Sugar support, it does does not appear to have been removed from current releases of Telepathy, only telepathy-next. 

Fedora Rawhide/34 includes telepathy-gabble 0.18.4, telepathy-salut 0.8.1, telepathy-glib 0.24.1, and python3-gwebsockets 0.7

**Comment by quozl** [comment]
Thanks.  That eliminates my guess.  It still needs diagnosis by debugging Telepathy, by testing an older version of Telepathy, or by reviewing Telepathy commits between the last working version and now.  To be sure you have the same problem as described by this issue, the Telepathy Salut process id will change between when the shared activity is running, and when it is stopped.  If process crash dumps are configured, then a core file will be made.

**Comment by aperezbios** [comment]
This also happens when a shared activity has NOT been stopped, so the bug description should be updated to reflect that, since the scope is significantly larger. 

Here's the log output I get from Sugar 0.118 (SoaS Fedora 34 prerelease): 
`Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/dbus/connection.py", line 606, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
  File "/usr/lib/python3.9/site-packages/jarabe/model/neighborhood.py", line 301, in __conn_get_interfaces_reply_cb
    self._connection[interface] = dbus.Interface(
TypeError: 'NoneType' object does not support item assignment`

**Comment by chimosky** [comment]
@aperezbios when a shared activity hasn't been stopped on one of the shared instances?

**Comment by aperezbios** [comment]
@chimosky when simply looking at the neighborhood view (with jabber.sugarlabs.org configured as the collaboration server)

**Comment by aperezbios** [comment]
Here is the contents of my salut.log file, after configuring debugging:

`
(process:1043): tp-glib/proxy-DEBUG: 09:51:20.541: tp_proxy_dispose: 0x561126ee39c0
(process:1043): tp-glib/proxy-DEBUG: 09:51:20.545: tp_proxy_invalidate: 0x561126ee39c0: Proxy unreferenced
(process:1043): tp-glib/proxy-DEBUG: 09:51:20.545: tp_proxy_finalize: 0x561126ee39c0
(process:1043): salut-DEBUG: 09:51:20.545: salut_plugin_loader_probe: probing /usr/lib64/telepathy/salut-0/plugins
(process:1043): tp-glib/proxy-DEBUG: 09:51:20.545: tp_proxy_dispose: 0x561126ee3a50
(process:1043): tp-glib/proxy-DEBUG: 09:51:20.545: tp_proxy_invalidate: 0x561126ee3a50: Proxy unreferenced
(process:1043): tp-glib/proxy-DEBUG: 09:51:20.545: tp_proxy_finalize: 0x561126ee3a50
(process:1043): salut-DEBUG: 09:51:20.545: salut_plugin_loader_probe: Error opening directory ?/usr/lib64/telepathy/salut-0/plugins?: No such file or directory
(telepathy-salut:1043): tp-glib-DEBUG: 09:51:20.551: started version 0.8.1 (telepathy-glib version 0.24.2)
(telepathy-salut:1043): tp-glib/params-DEBUG: 09:51:20.552: tp_base_protocol_sanitize_parameters: using specified value for nickname: "Alex"
(telepathy-salut:1043): tp-glib/params-DEBUG: 09:51:20.552: tp_base_protocol_sanitize_parameters: using specified value for first-name: ""
(telepathy-salut:1043): tp-glib/params-DEBUG: 09:51:20.552: tp_base_protocol_sanitize_parameters: using specified value for last-name: ""
(telepathy-salut:1043): tp-glib/params-DEBUG: 09:51:20.552: tp_base_protocol_sanitize_parameters: using specified value for jid: "e784be58eaac9694166e939e30d272e9d5f8b800@jabber.sugarlabs.org"
(telepathy-salut:1043): tp-glib/params-DEBUG: 09:51:20.552: tp_base_protocol_sanitize_parameters: using specified value for published-name: "e784be58"
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:20.556: tp_presence_mixin_class_init: called.
(telepathy-salut:1043): salut-DEBUG: 09:51:20.559: gabble_capabilities_init: 0x561126f0c1c0
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:20.561: tp_presence_mixin_init: called.
(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:20.578: tp_base_connection_register: 0x561126f0c1c0: bus name org.freedesktop.Telepathy.Connection.salut.local_xmpp.e784be58; object path /org/freedesktop/Telepathy/Connection/salut/local_xmpp/e784be58
(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:20.587: tp_presence_mixin_get_contacts_dbus_property: called.
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:20.587: tp_presence_mixin_get_simple_presence_dbus_property: called.
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:20.587: check_status_available: requested status offline is not available
(telepathy-salut:1043): salut-DEBUG: 09:51:20.588: salut_connection_update_capabilities: enter
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:20.589: tp_presence_mixin_simple_presence_set_presence: called.
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:20.589: check_for_status: Found status "available", checking if it's available...
(telepathy-salut:1043): salut-DEBUG: 09:51:20.590: salut_connection_update_capabilities: enter
(telepathy-salut:1043): salut-DEBUG: 09:51:20.597: salut_presence_cache_learn_caps: learning http://telepathy.freedesktop.org/caps#9lCQ5h7/WCRiOzEwFNec7Rx0w7o=

(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:20.606: tp_base_connection_change_status: was 4294967295, now 1, for reason 1
(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:20.606: tp_base_connection_change_status: emitting status-changed to 1, for reason 1
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.546: tp_presence_mixin_emit_one_presence_update: called.
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.546: tp_presence_mixin_emit_presence_update: called.
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.546: construct_presence_hash: called.
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.546: construct_simple_presence_hash: called.
(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:21.546: tp_base_connection_change_status: was 1, now 0, for reason 0
(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:21.547: tp_base_connection_change_status: emitting status-changed to 0, for reason 0
(telepathy-salut:1043): salut-DEBUG: 09:51:21.547: sidecars_conn_status_changed_cb: connected; requesting sidecars from plugins
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.549: tp_presence_mixin_get_simple_presence_dbus_property: called.
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.550: check_status_available: requested status offline is not available
(telepathy-salut:1043): salut-DEBUG: 09:51:21.550: salut_connection_set_aliases: Setting my alias to: Alex
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.550: tp_presence_mixin_simple_presence_set_presence: called.
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.550: check_for_status: Found status "available", checking if it's available...
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.551: tp_presence_mixin_emit_one_presence_update: called.
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.551: tp_presence_mixin_emit_presence_update: called.
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.551: construct_presence_hash: called.
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:21.551: construct_simple_presence_hash: called.
(telepathy-salut:1043): salut-DEBUG: 09:51:21.951: salut_connection_update_capabilities: enter
(telepathy-salut:1043): salut-DEBUG: 09:51:21.951: salut_ft_manager_represent_client: client org.freedesktop.Telepathy.Client.Sugar.FileTransfer supports file transfer
(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:21.959: channel_request_new: New channel request at 0x561126ed9700: ctype=org.freedesktop.Telepathy.Channel.Type.ContactList htype=3 handle=1 suppress=0
(telepathy-salut:1043): tp-glib/groups-DEBUG: 09:51:21.960: tp_group_mixin_change_flags: emitting group flags changed
  added    : [PROPERTIES]
  removed  : []
  flags now: [PROPERTIES|MEMBERS_CHANGED_DETAILED]

(telepathy-salut:1043): tp-glib/groups-DEBUG: 09:51:21.960: tp_group_mixin_change_flags: No change: 6144 includes all the bits of 0 and none of 0
(telepathy-salut:1043): salut-DEBUG: 09:51:22.558: salut_contact_manager_all_for_now_cb: Contact list received
(telepathy-salut:1043): tp-glib/groups-DEBUG: 09:51:22.558: tp_group_mixin_change_flags: emitting group flags changed
  added    : [PROPERTIES]
  removed  : []
  flags now: [PROPERTIES|MEMBERS_CHANGED_DETAILED]

(telepathy-salut:1043): tp-glib/groups-DEBUG: 09:51:22.558: tp_group_mixin_change_flags: No change: 6144 includes all the bits of 0 and none of 0
(telepathy-salut:1043): tp-glib/contact-lists-DEBUG: 09:51:22.558: tp_base_contact_list_set_list_received: Initial contacts: 
(telepathy-salut:1043): tp-glib/groups-DEBUG: 09:51:22.558: change_members: not emitting signal, nothing changed
(telepathy-salut:1043): tp-glib/groups-DEBUG: 09:51:22.558: change_members: not emitting signal, nothing changed
(telepathy-salut:1043): tp-glib/groups-DEBUG: 09:51:22.558: change_members: not emitting signal, nothing changed
(telepathy-salut:1043): tp-glib/groups-DEBUG: 09:51:22.558: change_members: not emitting signal, nothing changed
(telepathy-salut:1043): tp-glib/groups-DEBUG: 09:51:22.558: change_members: not emitting signal, nothing changed
(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:22.558: satisfy_request: completing queued request 0x561126ed9700 with success, channel_type=org.freedesktop.Telepathy.Channel.Type.ContactList, handle_type=3, handle=1, suppress_handler=0
(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:22.558: channel_request_free: Freeing channel request at 0x561126ed9700: ctype=org.freedesktop.Telepathy.Channel.Type.ContactList htype=3 handle=1 suppress=0
(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:22.654: tp_base_connection_change_status: was 0, now 2, for reason 1
(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:22.654: tp_base_connection_change_status: emitting status-changed to 2, for reason 1
(telepathy-salut:1043): salut-DEBUG: 09:51:22.655: salut_im_factory_close_all: closing channels
(telepathy-salut:1043): salut-DEBUG: 09:51:22.656: salut_muc_manager_close_all: closing channels
(telepathy-salut:1043): salut-DEBUG: 09:51:22.656: salut_roomlist_manager_close_all: closing channels
(telepathy-salut:1043): salut-DEBUG: 09:51:22.669: salut_connection_shut_down: connection may still be open; closing it: 0x561126f0c1c0
(telepathy-salut:1043): salut-DEBUG: 09:51:22.669: closed_cb: connection properly closed
(telepathy-salut:1043): tp-glib/params-DEBUG: 09:51:22.669: connection_shutdown_finished_cb: dereferenced connection
(telepathy-salut:1043): salut-DEBUG: 09:51:22.669: salut_disco_dispose: dispose called
(telepathy-salut:1043): salut-DEBUG: 09:51:22.669: salut_presence_cache_dispose: dispose called
(telepathy-salut:1043): salut-DEBUG: 09:51:22.669: salut_presence_cache_finalize: called with 0x561126f0feb0
(telepathy-salut:1043): salut-DEBUG: 09:51:22.672: salut_contact_manager_dispose: Disposing contact manager
(telepathy-salut:1043): salut-DEBUG: 09:51:22.672: salut_muc_manager_close_all: closing channels
(telepathy-salut:1043): salut-DEBUG: 09:51:22.673: salut_roomlist_manager_close_all: closing channels
(telepathy-salut:1043): tp-glib/presence-DEBUG: 09:51:22.673: tp_presence_mixin_finalize: 0x561126f0c1c0
(telepathy-salut:1043): tp-glib/connection-DEBUG: 09:51:22.673: tp_contacts_mixin_finalize: 0x561126f0c1c0
(telepathy-salut:1043): salut-DEBUG: 09:51:22.673: gabble_capabilities_finalize: 0x561126f0c1c0
(telepathy-salut:1043): salut-DEBUG: 09:51:22.673: salut_connection_finalize: Finalizing connection
(telepathy-salut:1043): tp-glib-DEBUG: 09:51:27.674: no connections, and timed out
tp-glib-Message: 09:51:27.675: Exiting
(telepathy-salut:1043): tp-glib/proxy-DEBUG: 09:51:27.675: tp_proxy_dispose: 0x561126ee3ae0
(telepathy-salut:1043): tp-glib/proxy-DEBUG: 09:51:27.675: tp_proxy_invalidate: 0x561126ee3ae0: Proxy unreferenced
(telepathy-salut:1043): tp-glib/proxy-DEBUG: 09:51:27.675: tp_proxy_finalize: 0x561126ee3ae0
`

**Comment by aperezbios** [comment]
Bizarrely, the simple act of setting G_MESSAGES_DEBUG="all" (and rebooting, or killing jarabe.py to induce sugar desktop re-start) in /etc/environment seems to "fix" the problem, although I've no idea why, as it makes no sense.

**Comment by chimosky** [comment]
> @chimosky when simply looking at the neighborhood view (with jabber.sugarlabs.org configured as the collaboration server)

The first part of the error could be when no interface was returned which could happen when a connection hasn't been made but that'll throw an `Disconnected` error instead. @quozl might have a better insight as to the possible causes of this.

I've seen the last line of the error and I can't remember the cause of that and I think there used to be an open issue for it.

> Bizarrely, the simple act of setting G_MESSAGES_DEBUG="all" (and rebooting, or killing jarabe.py to induce sugar desktop re-start) in /etc/environment seems to "fix" the problem, although I've no idea why, as it makes no sense.

Are you saying when you do this the jabber server connection gets created successfully and those errors aren't shown in the logs anymore?

**Comment by quozl** [comment]
Oh, okay.  No, I'm not using jabber.sugarlabs.org at all, I'm concentrating only on link-local peer to peer, aka Telepathy Salut.  If you're using jabber.sugarlabs.org, then you're using Telepathy Gabble.  Two very different underlying software components.  I'm interested to know what causes Salut to unexpectedly terminate, but I've not even got as far as analysing the core dump.

**Comment by aperezbios** [comment]
@quozl should we separate these issues, one for telepahthy-gabble, and one for telepathy-salut? We need to figure out why setting G_MESSAGES_DEBUG="all" in /etc/environment (and then restarting jarabe), results in Sugar (using) telepathy-gabble seeing neighbors/peers.

**Comment by quozl** [comment]
Thanks for asking.  I don't mind either way.  It's not like were not solving the problem because the issue is too hard to read.  Speculating; we're not solving it because (a) it is a Telepathy problem rather than a Sugar problem (most likely), (b) Telepathy is written in C and we have attracted primarily Python developers, and (c) those of us with C skills haven't had the time to investigate.

If you do split the issues, create new ones that condense and summarise the observations in each scenario, with a link back to this issue, then we can close this issue.

**Comment by vamshikiran065-jpg** [comment]
Hi, I’m interested in working on this issue and have understood the requirements. 
Could you please assign it to me?

**Comment by quozl** [comment]
No, we do not assign issues.  You're welcome to work on it, but we make no promises that we will listen to you exclusively.
