### ISSUE TITLE
Traceback related to #840.

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/sugar#843]
```
1561781386.846467 ERROR root: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.17 was not provided by any .service files
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jarabe/model/filetransfer.py", line 325, in file_transfer_available
    CONNECTION_INTERFACE_REQUESTS)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.17 was not provided by any .service files
1561781524.453747 ERROR root: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.17 was not provided by any .service files
Traceback (most recent call last):
```
**Reproducer**
* Share a file between two sugar instances from journal.
* Reproduce #840 
* Check shell.logs

**Comment by quozl** [comment]
It's probably #840.  Would require `dbus-monitor` to verify, but not sure of why we would need to.  During the time that one of the Telepathy processes is dead or dumping core, the numeric service name won't be valid.  Test again once #840 is fixed.
