### ISSUE TITLE
Copy to Documents fails with TypeError

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#853]
```log
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/jarabe/journal/palettes.py", line 398, in __copy_to_volume_cb
    model.copy(metadata, self._mount_point)
  File "/usr/lib/python3.7/dist-packages/jarabe/journal/model.py", line 700, in copy
    ready_callback=ready_callback)
  File "/usr/lib/python3.7/dist-packages/jarabe/journal/model.py", line 740, in write
    metadata, file_path, ready_callback=ready_callback)
  File "/usr/lib/python3.7/dist-packages/jarabe/journal/model.py", line 859, in _write_entry_on_external_device
    os.write(fh, metadata_json)
TypeError: a bytes-like object is required, not 'str'
```

Object being copied was from Browse activity.

**Comment by quozl** [comment]
Fixed in https://github.com/sugarlabs/sugar/commit/68321ffe4f53543d9e4f1533ce07164afa303d95
