### ISSUE TITLE
Cannot take screenshot

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#857]
Reproducer: open Frame, right-click on display, select _Take a screenshot_.

Expected result: screenshot added to Journal

Observed result: no screenshot added to Journal

shell.log
```log
Traceback (most recent call last):
  File "/usr/share/sugar/extensions/deviceicon/display.py", line 231, in __take_screenshot_cb
    take_screenshot()
  File "/usr/lib/python3.7/dist-packages/jarabe/model/screenshot.py", line 80, in take_screenshot
    jobject.metadata['preview'] = _get_preview_data(screenshot_surface)
  File "/usr/lib/python3.7/dist-packages/jarabe/model/screenshot.py", line 118, in _get_preview_data
    preview_surface.write_to_png(preview_str)
jarabe.model.screenshot.IOError: error while writing to output stream
```

**Comment by quozl** [comment]
I've a fix for this.
