### ISSUE TITLE
TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#860]

**Comment by quozl** [comment]
```log
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/dbus/connection.py", line 604, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
  File "/usr/lib/python3.7/site-packages/jarabe/desktop/meshbox.py", line 298, in __get_devices_reply_cb
    self._check_device(dev_o)
  File "/usr/lib/python3.7/site-packages/jarabe/desktop/meshbox.py", line 317, in _check_device
    self._box.add_adhoc_networks(device)
  File "/usr/lib/python3.7/site-packages/jarabe/desktop/meshbox.py", line 552, in add_adhoc_networks
    self._adhoc_manager = get_adhoc_manager_instance()
  File "/usr/lib/python3.7/site-packages/jarabe/model/adhoc.py", line 35, in get_adhoc_manager_instance
    _adhoc_manager_instance = AdHocManager()
  File "/usr/lib/python3.7/site-packages/jarabe/model/adhoc.py", line 76, in __init__
    self._add_connection(channel)
  File "/usr/lib/python3.7/site-packages/jarabe/model/adhoc.py", line 199, in _add_connection
    settings.wireless.ssid = dbus.ByteArray(ssid)
TypeError: string argument without an encoding
```

Reported by @bhulsken.
