### ISSUE TITLE
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#863]
```log
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/jarabe/journal/listmodel.py", line 166, in do_get_value
    metadata = self._result_set.read()
  File "/usr/lib/python3.7/site-packages/jarabe/journal/model.py", line 152, in read
    entries, self._total_count = self.find(query)
  File "/usr/lib/python3.7/site-packages/jarabe/journal/model.py", line 226, in find
    byte_arrays=True)
  File "/usr/lib64/python3.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
```

Reported by @bhulsken

**Comment by quozl** [comment]
I've tried but unable to reproduce.

**Comment by quozl** [comment]
Caused by division now yielding a float, https://github.com/sugarlabs/sugar/issues/862.

**Comment by sanjay237** [comment]
@quozl Ran into this today, I'm running Sugar 0.116 (w/ Debian Buster) on a VM.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/jarabe/journal/listmodel.py", line 132, in do_iter_n_children
    return self._result_set.length
  File "/usr/lib/python3.7/dist-packages/jarabe/journal/model.py", line 112, in get_length
    entries, self._total_count = self.find(query)
  File "/usr/lib/python3.7/dist-packages/jarabe/journal/model.py", line 226, in find
    byte_arrays=True)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.7/dist-packages/carquinyol/datastore.py", line 409, in find
    metadata = self._metadata_store.retrieve(uid, properties)
  File "/usr/lib/python3.7/dist-packages/carquinyol/metadatastore.py", line 84, in retrieve
    metadata[key] = dbus.Int32(value)
ValueError: invalid literal for int() with base 10: b''
```

**Comment by quozl** [comment]
Thanks, but very different in that it is a ValueError instead of a TypeError.  It does look like what was reported in http://lists.sugarlabs.org/archive/soas/2020-February/003035.html

It looks likely to be an activity problem; in a journal object the metadata for filesize, creation_time, or timestamp contains invalid data.  I suggest inspecting the datastore metadata on disk.   I suggest trying to find out how to make it happen.
