### ISSUE TITLE
jarabe.model.screenshot.IOError: error while writing to output stream

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#867]
Screenshot does not work; there is no journal object created.  shell.log contains

```log
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/jarabe/view/keyhandler.py", line 223, in _key_pressed_cb
    action.handle_key_press(key)
  File "/usr/share/sugar/extensions/globalkey/screenshot.py", line 23, in handle_key_press
    take_screenshot()
  File "/usr/lib/python3.7/dist-packages/jarabe/model/screenshot.py", line 80, in take_screenshot
    jobject.metadata['preview'] = _get_preview_data(screenshot_surface)
  File "/usr/lib/python3.7/dist-packages/jarabe/model/screenshot.py", line 118, in _get_preview_data
    preview_surface.write_to_png(preview_str)
jarabe.model.screenshot.IOError: error while writing to output stream
```

**Comment by nswarup14** [comment]
@quozl 
Seems like a duplication of the Issue #857

**Comment by quozl** [comment]
Probably.

**Comment by Aniket21mathur** [comment]
The tracebacks for both are looking identical, probably both the issues will have the same fix.

**Comment by quozl** [comment]
I've a fix for this.
