### ISSUE TITLE
Scattered Favorites view at Home does not show

### ISSUE THREAD

**Issue by happytobe2e** [sugarlabs/sugar#932]
Dear Sugar Labs Community,

When loading the scattered Favorites view on the Home screen, I do not get randomly placed icons. Instead, I get the following error message in my `shell.log`:

    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/jarabe/desktop/viewcontainer.py", line 69, in do_size_allocate
        self._layout.allocate_children(allocation, self._children)
      File "/usr/lib/python3.9/site-packages/jarabe/desktop/favoriteslayout.py", line 250, in allocate_children
        name_hash = hashlib.md5(child.get_bundle_id().decode())
    AttributeError: 'str' object has no attribute 'decode'

For your information, I am running Fedora Rawhide.

**Comment by quozl** [comment]
Thanks.  It was fixed in commit 118fe73eee4177833dc692e1172451656f580b7f.

**Comment by happytobe2e** [comment]
Closing as duplicate of bug #923.
