### ISSUE TITLE
Detect Python 2 activities

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#991]
Sugar on a Python 3 platform does not detect and warn about Python 2 activities; they are installed, but fail to start, and the logs contain nothing.

**Comment by amannaik247** [comment]
Hey @quozl could you please checkout pr #992 regarding this issue

**Comment by Maryam3107** [comment]
> Sugar on a Python 3 platform does not detect and warn about Python 2 activities; they are installed, but fail to start, and the logs contain nothing.

I would like to work on this issue. kindly assign this to me

**Comment by chimosky** [comment]
Hi @Maryam3107 we don't assign issues, anyone is free to work on the issue. 

Looking forward to your contribution.

**Comment by quozl** [comment]
Why don't you test Sugar and find out?  Or you could look at the commits in the repository.

**Comment by Maryam3107** [comment]
I will trynsoon

**Comment by ahmadtariq1** [comment]
Hey @quozl, please review this:

Modifying sugar-toolkit-gtk3 so that before installing the activity in the designated folder we unzip the activity to a temporary folder.(or other possible efficient alternatives)

> Check for shebang:

If **#!/usr/bin/python3** , then it should continue as before
Else if **#!/usr/bin/env python** or (in rare cases) -> **#!/usr/bin/env python2** 

> then we scan the script and look for old python2 code.

If found, we can stop and write in logs or even display error messages.
Kindly let me know if this is the right approach so that I start working on it.

**Comment by quozl** [comment]
Protection at install stage is not useful.  Users may upgrade Sugar on an existing system.  Bundles may be unpacked by school or department scripting.

Also, you cannot determine the required version of Python using the `#!` as some distributions use `python` for either Python 2 or Python 3.

Also, `/usr/bin/env` adds no value.  It is ritualistic.

Have you even tried to install and run a Python 2 activity on a Python 3 bound Sugar?

**Comment by quozl** [comment]
Puzzled by the lack of progress on this issue, and the number of desires, speculations and misdirections we've had to endure.  I'll push the issue along now.

Tested on Ubuntu 24.04 Sugar 0.121 without Python 2, with Slider Puzzle activity _master_ branch before the port to Python 3 (95aaa6d).  Results are;

* Sugar Home View displays the launcher animation for about a minute,
* Launcher eventually reports "Slider Puzzle failed to start." with a "Stop" button,
* Log file org.worldwideworkshop.olpc.SliderPuzzle-1.log contains nothing,
* Log file shell.log contains;

```log
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 590, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityfactory.py", line 251, in _activate_reply_handler
    self._create_activity()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityfactory.py", line 228, in _create_activity
    child = subprocess.Popen([str(s) for s in command],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sugar-activity'
```

If the activity is started in Terminal using the `sugar-activity3` debugging method, the result is "Activity written for Python 2, consider porting to Python 3".  So clearly this has been detected by src/sugar3/activity/activityinstance.py

So faults are;
* the failure to run the activity is not handled,
* the launcher continues animating long after the failure,
* the activity log doesn't even have a gravestone.

What is needed;
* [ ] reduce the launcher animation timeout to about ten seconds,
* [ ] handle the FileNotFoundError exception,
* [ ] detect the "sugar-activity" in the exception message, write a line to the log, and display an explanation for failed to start.

Anyone interested in doing this?

**Comment by ahmadtariq1** [comment]
> Also, you cannot determine the required version of Python using the `#!` as some distributions use `python` for either Python 2 or Python 3.
I meant the same thing, I guess it didn’t come out clearly.
> Also, `/usr/bin/env` adds no value. It is ritualistic.
Copied from the top of the files to simply provide an example.
> Have you even tried to install and run a Python 2 activity on a Python 3 bound Sugar?
Yes I have ran an older version of calculate activity, logs were empty.  Tried using strace, but I didn’t have time to dig deeper..
> Protection at install stage is not useful. Users may upgrade Sugar on an existing system. Bundles may be unpacked by school or department scripting.
Your solution makes more sense, handling this in launch stage.

I'll try to come up with a pr.

**Comment by ahmadtariq1** [comment]
![Image](https://github.com/user-attachments/assets/7d60c488-8c77-40c6-8035-c6f1d5d69c7b)


@quozl is this enough or do I have to display in ui as well?
Currently it displays: "Failed to start".
Would really appreciate a swift response.

**Comment by quozl** [comment]
What's the rush?  We've had the problem for years.

The message should be similar in nature to the existing failed to start message, but with an explanation as to why it failed.  The message should be included in the translation catalog.

**Comment by ahmadtariq1** [comment]
Hi @quozl, sorry for keeping at it with this! I’ve completed all the requirements. For the last part, I pulled the error from the log file (to communicate failure reason) in launcher.py so that we have a custom message for the python2 failure. It works, though it has its drawbacks but it’s simple and practical enough. The other idea is changing the shell file to add a failure_reason attribute to the activity class, which seems a lot more robust. Which one do you think would suffice?

**Comment by chimosky** [comment]
If you have something that works, the best way to ask for a review is to open a PR.

**Comment by mohitnandaniya-devloper** [comment]
this is test subject

**Comment by mohitnandaniya-devloper** [comment]
#999 helpful
it's just helpfull comment

**Comment by vanshjohri09-collab** [comment]
thanks for the feedback, @quozl 🙏. You’re right that reducing the timeout too aggressively could cause slow‑starting activities to be marked as failed unnecessarily.
To refine my approach, I’ll focus on:
- Error Handling: Catching the FileNotFoundError when sugar-activity is missing, and logging a clear explanation.
- Message Wording: Adding a learner‑friendly message (included in the translation catalog) so that teachers and learners understand why the activity didn’t start, without developer jargon. Example:
“This activity was made for an older version. It cannot run on this computer. Please ask your teacher for an updated version.”
For the timeout, instead of a fixed 10 seconds, I’ll explore a more balanced solution (e.g., configurable or adaptive timeout) so that genuinely slow activities aren’t misclassified as failures.
I’ll prepare a PR with these improvements, and I’ll also review the open PRs linked to this issue as part of contributing responsibly.
Thanks again for the guidance
